version: '2'
services:
  dotledger:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - "db"
    environment:
      - DB_PASSWORD=123456
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=dot_ledger
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=dot_ledger
